/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    plans: Plan;
    subscriptions: Subscription;
    posts: Post;
    objects: Object;
    feedback: Feedback;
    categories: Category;
    bids: Bid;
    offers: Offer;
    favorites: Favorite;
    transactions: Transaction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    objects: ObjectsSelect<false> | ObjectsSelect<true>;
    feedback: FeedbackSelect<false> | FeedbackSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    bids: BidsSelect<false> | BidsSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    favorites: FavoritesSelect<false> | FavoritesSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'particulier' | 'professionnel' | 'admin';
  firstName: string;
  lastName: string;
  profilePhoto?: (number | null) | Media;
  address: {
    street: string;
    city: string;
    postalCode: string;
    country: string;
  };
  isOver18?: boolean | null;
  companyName?: string | null;
  siret?: string | null;
  /**
   * K-Bis, avis de situation INSEE ou autre document officiel
   */
  officialDocument?: (number | null) | Media;
  website?: string | null;
  socialMedia?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    twitter?: string | null;
  };
  /**
   * Requis pour les professionnels (achats/enchères) et les particuliers (ventes)
   */
  bankDetails?: {
    /**
     * Format: FR76 1234 5678 9012 3456 7890 123
     */
    iban?: string | null;
    /**
     * Code BIC/SWIFT de la banque (8 ou 11 caractères)
     */
    bic?: string | null;
    /**
     * Nom du titulaire du compte bancaire
     */
    accountHolderName?: string | null;
    /**
     * Vérifié par l'administrateur
     */
    bankDetailsVerified?: boolean | null;
  };
  acceptedTerms?: boolean | null;
  acceptedMandate?: boolean | null;
  acceptedGDPR?: boolean | null;
  newsletterSubscription?: boolean | null;
  accountStatus?: ('pending' | 'active' | 'suspended' | 'rejected') | null;
  currentSubscription?: (number | null) | Subscription;
  subscriptionStatus?: ('active' | 'trialing' | 'suspended' | 'canceled' | 'expired' | 'restricted') | null;
  subscriptionEndDate?: string | null;
  stripeCustomerId?: string | null;
  stripeSubscriptionId?: string | null;
  /**
   * ID du moyen de paiement Stripe (carte bancaire)
   */
  stripePaymentMethodId?: string | null;
  /**
   * Requis pour enchérir (professionnels uniquement)
   */
  hasValidPaymentMethod?: boolean | null;
  /**
   * Computed automatically (pro + active subscription + valid bank details).
   */
  canBid?: boolean | null;
  /**
   * Computed automatically based on role and validation.
   */
  canSell?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Historique et gestion des abonnements utilisateurs
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: number;
  user: number | User;
  plan: number | Plan;
  status: 'active' | 'trialing' | 'suspended' | 'canceled' | 'expired';
  currentPeriodStart: string;
  currentPeriodEnd: string;
  trialEnd?: string | null;
  canceledAt?: string | null;
  /**
   * L'abonnement sera automatiquement renouvelé à la fin de la période
   */
  autoRenew?: boolean | null;
  paymentMethod?: ('card' | 'paypal' | 'bank_transfer' | 'free' | 'trial') | null;
  /**
   * Montant réellement payé pour cette période
   */
  amount?: number | null;
  /**
   * Notes internes sur cet abonnement
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestion des forfaits d'abonnement pour la plateforme
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  /**
   * Nom affiché du forfait (ex: "Forfait Particulier", "Forfait Professionnel")
   */
  name: string;
  /**
   * Identifiant technique unique (ex: "particulier", "professionnel")
   */
  slug: string;
  /**
   * À quel type d'utilisateur s'applique ce forfait
   */
  userType: 'particulier' | 'professionnel';
  /**
   * Prix en euros par mois. Mettre 0 pour gratuit.
   */
  price: number;
  /**
   * Nombre de jours d'essai gratuit. Mettre 0 pour aucune période d'essai.
   */
  trialPeriodDays?: number | null;
  /**
   * Description complète du forfait et de ses avantages
   */
  description?: string | null;
  /**
   * Liste des fonctionnalités incluses dans ce forfait
   */
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Désactiver pour masquer ce forfait (sans le supprimer)
   */
  isActive?: boolean | null;
  /**
   * Forfait attribué automatiquement lors de l'inscription
   */
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "objects".
 */
export interface Object {
  id: number;
  name: string;
  /**
   * Category of the object
   */
  category: number | Category;
  dimensions: {
    height: number;
    width: number;
    depth: number;
    weight: number;
  };
  description: string;
  documents?:
    | {
        name: string;
        file: number | Media;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  photos: {
    name: string;
    image: number | Media;
    id?: string | null;
  }[];
  seller?: (number | null) | User;
  saleMode: 'quick_sale' | 'auction';
  quickSalePrice?: number | null;
  auctionStartPrice?: number | null;
  auctionEndDate?: string | null;
  status: 'draft' | 'active' | 'sold' | 'expired' | 'removed';
  /**
   * Minimum price required for the object to be sold
   */
  reservePrice?: number | null;
  currentBidAmount?: number | null;
  currentBidder?: (number | null) | User;
  bidCount?: number | null;
  viewCount?: number | null;
  favoriteCount?: number | null;
  /**
   * Number of times the auction end was extended by 10 minutes
   */
  auctionExtensions?: number | null;
  publishedAt?: string | null;
  soldAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL-friendly identifier (auto-generated from name if left empty)
   */
  slug: string;
  description?: string | null;
  /**
   * Only active categories are visible in filters
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback".
 */
export interface Feedback {
  id: number;
  /**
   * Utilisateur ayant donné l'avis
   */
  user: number | User;
  /**
   * Note en étoiles (1 à 5)
   */
  stars: number;
  /**
   * Note NPS (1 à 10)
   */
  npsScore: number;
  /**
   * Commentaires et suggestions
   */
  comment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bids".
 */
export interface Bid {
  id: number;
  object: number | Object;
  /**
   * Automatically set to current user
   */
  bidder: number | User;
  amount: number;
  /**
   * Maximum amount for automatic bidding
   */
  maxAutoBidAmount?: number | null;
  /**
   * Current status of the bid
   */
  status: 'pending' | 'highest' | 'outbid' | 'won' | 'lost' | 'canceled';
  /**
   * How the bid was placed
   */
  source: 'manual' | 'auto';
  /**
   * When the bid was placed
   */
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  object: number | Object;
  /**
   * Automatically set to current user
   */
  buyer: number | User;
  amount: number;
  /**
   * Message to the seller (will be filtered for contact information)
   */
  message?: string | null;
  /**
   * Current status of the offer
   */
  status: 'pending' | 'accepted' | 'rejected' | 'expired';
  /**
   * When the offer expires
   */
  expiresAt?: string | null;
  /**
   * When the offer was created
   */
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites".
 */
export interface Favorite {
  id: number;
  /**
   * Automatically set to current user
   */
  user: number | User;
  object: number | Object;
  /**
   * When the favorite was added
   */
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  object: number | Object;
  buyer: number | User;
  seller: number | User;
  /**
   * Final sale price of the object
   */
  finalPrice: number;
  /**
   * Commission charged to buyer (from Settings)
   */
  buyerCommission: number;
  /**
   * Commission deducted from seller (from Settings)
   */
  sellerCommission: number;
  shippingCost?: number | null;
  /**
   * Total paid by buyer (finalPrice + buyerCommission + shippingCost)
   */
  totalAmount: number;
  /**
   * Amount received by seller (finalPrice - sellerCommission)
   */
  sellerAmount: number;
  paymentIntentId?: string | null;
  checkoutSessionId?: string | null;
  /**
   * Stripe payment status
   */
  paymentStatus: 'pending' | 'held' | 'released' | 'refunded';
  /**
   * Current transaction status
   */
  status:
    | 'payment_pending'
    | 'payment_held'
    | 'awaiting_shipping'
    | 'in_transit'
    | 'delivered'
    | 'completed'
    | 'cancelled'
    | 'disputed';
  shippingAddress?: {
    street?: string | null;
    city?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  billingAddress?: {
    street?: string | null;
    city?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  /**
   * Name of the shipping carrier
   */
  shippingCarrier?: string | null;
  /**
   * Shipping tracking number
   */
  trackingNumber?: string | null;
  /**
   * When the payment was completed
   */
  paidAt?: string | null;
  /**
   * When the object was shipped
   */
  shippedAt?: string | null;
  /**
   * When the object was delivered
   */
  deliveredAt?: string | null;
  /**
   * When the transaction was completed (funds released)
   */
  completedAt?: string | null;
  /**
   * Internal notes for administrators
   */
  notes?: string | null;
  /**
   * When the transaction was created
   */
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: number | Subscription;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'objects';
        value: number | Object;
      } | null)
    | ({
        relationTo: 'feedback';
        value: number | Feedback;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'bids';
        value: number | Bid;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null)
    | ({
        relationTo: 'favorites';
        value: number | Favorite;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  firstName?: T;
  lastName?: T;
  profilePhoto?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        postalCode?: T;
        country?: T;
      };
  isOver18?: T;
  companyName?: T;
  siret?: T;
  officialDocument?: T;
  website?: T;
  socialMedia?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        twitter?: T;
      };
  bankDetails?:
    | T
    | {
        iban?: T;
        bic?: T;
        accountHolderName?: T;
        bankDetailsVerified?: T;
      };
  acceptedTerms?: T;
  acceptedMandate?: T;
  acceptedGDPR?: T;
  newsletterSubscription?: T;
  accountStatus?: T;
  currentSubscription?: T;
  subscriptionStatus?: T;
  subscriptionEndDate?: T;
  stripeCustomerId?: T;
  stripeSubscriptionId?: T;
  stripePaymentMethodId?: T;
  hasValidPaymentMethod?: T;
  canBid?: T;
  canSell?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  userType?: T;
  price?: T;
  trialPeriodDays?: T;
  description?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  isActive?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  user?: T;
  plan?: T;
  status?: T;
  currentPeriodStart?: T;
  currentPeriodEnd?: T;
  trialEnd?: T;
  canceledAt?: T;
  autoRenew?: T;
  paymentMethod?: T;
  amount?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "objects_select".
 */
export interface ObjectsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  dimensions?:
    | T
    | {
        height?: T;
        width?: T;
        depth?: T;
        weight?: T;
      };
  description?: T;
  documents?:
    | T
    | {
        name?: T;
        file?: T;
        description?: T;
        id?: T;
      };
  photos?:
    | T
    | {
        name?: T;
        image?: T;
        id?: T;
      };
  seller?: T;
  saleMode?: T;
  quickSalePrice?: T;
  auctionStartPrice?: T;
  auctionEndDate?: T;
  status?: T;
  reservePrice?: T;
  currentBidAmount?: T;
  currentBidder?: T;
  bidCount?: T;
  viewCount?: T;
  favoriteCount?: T;
  auctionExtensions?: T;
  publishedAt?: T;
  soldAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback_select".
 */
export interface FeedbackSelect<T extends boolean = true> {
  user?: T;
  stars?: T;
  npsScore?: T;
  comment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bids_select".
 */
export interface BidsSelect<T extends boolean = true> {
  object?: T;
  bidder?: T;
  amount?: T;
  maxAutoBidAmount?: T;
  status?: T;
  source?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  object?: T;
  buyer?: T;
  amount?: T;
  message?: T;
  status?: T;
  expiresAt?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites_select".
 */
export interface FavoritesSelect<T extends boolean = true> {
  user?: T;
  object?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  object?: T;
  buyer?: T;
  seller?: T;
  finalPrice?: T;
  buyerCommission?: T;
  sellerCommission?: T;
  shippingCost?: T;
  totalAmount?: T;
  sellerAmount?: T;
  paymentIntentId?: T;
  checkoutSessionId?: T;
  paymentStatus?: T;
  status?: T;
  shippingAddress?:
    | T
    | {
        street?: T;
        city?: T;
        postalCode?: T;
        country?: T;
      };
  billingAddress?:
    | T
    | {
        street?: T;
        city?: T;
        postalCode?: T;
        country?: T;
      };
  shippingCarrier?: T;
  trackingNumber?: T;
  paidAt?: T;
  shippedAt?: T;
  deliveredAt?: T;
  completedAt?: T;
  notes?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Paramètres globaux de la plateforme (commissions, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Commission percentage added to the final price for buyers (default: 3%)
   */
  globalBuyerCommission: number;
  /**
   * Commission percentage deducted from the final price for sellers (default: 2%)
   */
  globalSellerCommission: number;
  /**
   * Default duration in days if not specified (default: 7)
   */
  defaultAuctionDuration: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  globalBuyerCommission?: T;
  globalSellerCommission?: T;
  defaultAuctionDuration?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}