/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    plans: Plan;
    subscriptions: Subscription;
    posts: Post;
    feedback: Feedback;
    objects: Object;
    bids: Bid;
    categories: Category;
    settings: Setting;
    transactions: Transaction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    feedback: FeedbackSelect<false> | FeedbackSelect<true>;
    objects: ObjectsSelect<false> | ObjectsSelect<true>;
    bids: BidsSelect<false> | BidsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'particulier' | 'professionnel' | 'admin';
  firstName: string;
  lastName: string;
  profilePhoto?: (number | null) | Media;
  address: {
    street: string;
    city: string;
    postalCode: string;
    country: string;
  };
  isOver18?: boolean | null;
  companyName?: string | null;
  siret?: string | null;
  /**
   * K-Bis, avis de situation INSEE ou autre document officiel
   */
  officialDocument?: (number | null) | Media;
  website?: string | null;
  socialMedia?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    twitter?: string | null;
  };
  /**
   * Requis pour les professionnels (achats/enchères) et les particuliers (ventes)
   */
  bankDetails?: {
    /**
     * Format: FR76 1234 5678 9012 3456 7890 123
     */
    iban?: string | null;
    /**
     * Code BIC/SWIFT de la banque (8 ou 11 caractères)
     */
    bic?: string | null;
    /**
     * Nom du titulaire du compte bancaire
     */
    accountHolderName?: string | null;
    /**
     * Vérifié par l'administrateur
     */
    bankDetailsVerified?: boolean | null;
  };
  acceptedTerms?: boolean | null;
  acceptedMandate?: boolean | null;
  acceptedGDPR?: boolean | null;
  newsletterSubscription?: boolean | null;
  accountStatus?: ('pending' | 'active' | 'suspended' | 'rejected' | 'blocked') | null;
  /**
   * Bloquer l'accès du compte
   */
  isBlocked?: boolean | null;
  blockReason?:
    | (
        | 'fraud'
        | 'non_payment'
        | 'terms_violation'
        | 'inappropriate_behavior'
        | 'fake_documents'
        | 'repeated_disputes'
        | 'other'
      )
    | null;
  /**
   * Raison détaillée du blocage (interne)
   */
  blockReasonDetails?: string | null;
  blockedAt?: string | null;
  /**
   * Administrateur ayant effectué le blocage
   */
  blockedBy?: (number | null) | User;
  currentSubscription?: (number | null) | Subscription;
  subscriptionStatus?: ('active' | 'trialing' | 'suspended' | 'canceled' | 'expired' | 'restricted') | null;
  stripeCustomerId?: string | null;
  stripeSubscriptionId?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Historique et gestion des abonnements utilisateurs
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: number;
  user: number | User;
  plan: number | Plan;
  status: 'active' | 'trialing' | 'suspended' | 'canceled' | 'expired';
  currentPeriodStart: string;
  currentPeriodEnd: string;
  trialEnd?: string | null;
  canceledAt?: string | null;
  /**
   * L'abonnement sera automatiquement renouvelé à la fin de la période
   */
  autoRenew?: boolean | null;
  paymentMethod?: ('card' | 'paypal' | 'bank_transfer' | 'free') | null;
  /**
   * Montant réellement payé pour cette période
   */
  amount?: number | null;
  /**
   * Notes internes sur cet abonnement
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestion des forfaits d'abonnement pour la plateforme
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  /**
   * Nom affiché du forfait (ex: "Forfait Particulier", "Forfait Professionnel")
   */
  name: string;
  /**
   * Identifiant technique unique (ex: "particulier", "professionnel")
   */
  slug: string;
  /**
   * À quel type d'utilisateur s'applique ce forfait
   */
  userType: 'particulier' | 'professionnel';
  /**
   * Prix en euros par mois. Mettre 0 pour gratuit.
   */
  price: number;
  /**
   * Nombre de jours d'essai gratuit. Mettre 0 pour aucune période d'essai.
   */
  trialPeriodDays?: number | null;
  /**
   * Description complète du forfait et de ses avantages
   */
  description?: string | null;
  /**
   * Liste des fonctionnalités incluses dans ce forfait
   */
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Désactiver pour masquer ce forfait (sans le supprimer)
   */
  isActive?: boolean | null;
  /**
   * Forfait attribué automatiquement lors de l'inscription
   */
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback".
 */
export interface Feedback {
  id: number;
  /**
   * Utilisateur ayant donné l'avis
   */
  user: number | User;
  /**
   * Note en étoiles (1 à 5)
   */
  stars: number;
  /**
   * Note NPS (1 à 10)
   */
  npsScore: number;
  /**
   * Commentaires et suggestions
   */
  comment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "objects".
 */
export interface Object {
  id: number;
  name: string;
  /**
   * Sélectionner une catégorie depuis la liste (gérée par les admins)
   */
  category: number | Category;
  description: string;
  dimensions: {
    length: number;
    width: number;
    height: number;
    weight: number;
  };
  /**
   * Certificats d'authenticité, preuves d'achat, etc.
   */
  documents?:
    | {
        document: number | Media;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Minimum 10 photos, maximum 20
   */
  photos: {
    photo: number | Media;
    id?: string | null;
  }[];
  /**
   * Prix que vous souhaitez obtenir
   */
  price: number;
  saleMode: 'auction' | 'quick-sale';
  auctionConfig?: {
    /**
     * Par défaut : -10% du prix souhaité
     */
    startingPrice?: number | null;
    /**
     * Prix minimum pour vendre
     */
    reservePrice?: number | null;
    duration?: number | null;
    startDate?: string | null;
    endDate?: string | null;
    currentBid?: number | null;
    bidCount?: number | null;
  };
  seller: number | User;
  status: 'draft' | 'pending' | 'active' | 'sold' | 'withdrawn' | 'rejected' | 'expired';
  buyer?: (number | null) | User;
  soldPrice?: number | null;
  soldDate?: string | null;
  views?: number | null;
  favorites?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestion des catégories d'objets
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Nom affiché de la catégorie (ex: "Art Contemporain")
   */
  name: string;
  /**
   * Identifiant unique pour l'URL (ex: "art-contemporain")
   */
  slug: string;
  /**
   * Description de la catégorie
   */
  description?: string | null;
  /**
   * Icône de la catégorie (recommandé: SVG ou PNG transparent)
   */
  icon?: (number | null) | Media;
  /**
   * Image de présentation de la catégorie
   */
  image?: (number | null) | Media;
  /**
   * Pour créer une hiérarchie de catégories (sous-catégories)
   */
  parentCategory?: (number | null) | Category;
  /**
   * Ordre d'affichage (0 = premier)
   */
  order?: number | null;
  /**
   * Désactiver pour masquer la catégorie sans la supprimer
   */
  isActive?: boolean | null;
  /**
   * Mettre en avant cette catégorie sur la page d'accueil
   */
  featuredOnHome?: boolean | null;
  /**
   * Définir des commissions particulières pour cette catégorie (sinon, commissions globales)
   */
  customCommissions?: {
    useCustomCommissions?: boolean | null;
    buyerCommission?: number | null;
    sellerCommission?: number | null;
  };
  /**
   * Champs spécifiques à demander pour cette catégorie
   */
  formCustomization?: {
    /**
     * Ajouter des champs spécifiques pour cette catégorie
     */
    additionalFields?:
      | {
          fieldName: string;
          fieldLabel: string;
          fieldType: 'text' | 'number' | 'date' | 'checkbox' | 'select';
          isRequired?: boolean | null;
          id?: string | null;
        }[]
      | null;
    requireCertificate?: boolean | null;
    requireExpertise?: boolean | null;
  };
  /**
   * Nombre total d'objets dans cette catégorie
   */
  objectCount?: number | null;
  /**
   * Nombre d'enchères en cours dans cette catégorie
   */
  activeAuctionsCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bids".
 */
export interface Bid {
  id: number;
  object: number | Object;
  bidder: number | User;
  amount: number;
  bidType: 'manual' | 'automatic';
  /**
   * Si enchère automatique, montant maximum à enchérir
   */
  maxAutoBid?: number | null;
  status: 'active' | 'outbid' | 'winning' | 'lost';
  /**
   * Email de notification envoyé à l'enchérisseur
   */
  notified?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Paramètres globaux de la plateforme
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Nom du paramètre (ex: "Commissions Plateforme")
   */
  label: string;
  /**
   * Identifiant technique (ex: "platform_commissions")
   */
  key: string;
  globalCommissions?: {
    /**
     * Pourcentage de commission prélevé sur l'acheteur
     */
    buyerCommission: number;
    /**
     * Pourcentage de commission prélevé sur le vendeur
     */
    sellerCommission: number;
  };
  /**
   * Définir des commissions spécifiques par catégorie
   */
  categoryCommissions?:
    | {
        category: number | Category;
        buyerCommission: number;
        sellerCommission: number;
        id?: string | null;
      }[]
    | null;
  formConfig?: {
    /**
     * Liste des champs obligatoires dans le formulaire de dépôt
     */
    requiredFields?:
      | {
          fieldName: string;
          id?: string | null;
        }[]
      | null;
    minPhotos?: number | null;
    maxPhotos?: number | null;
    enableCertificates?: boolean | null;
    enableExpertise?: boolean | null;
  };
  generalSettings?: {
    /**
     * Activer le mode maintenance (site inaccessible sauf pour les admins)
     */
    maintenanceMode?: boolean | null;
    /**
     * Autoriser les nouvelles inscriptions
     */
    registrationEnabled?: boolean | null;
    auctionEnabled?: boolean | null;
    quickSaleEnabled?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestion de la comptabilité et des transactions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  /**
   * Identifiant unique de la transaction
   */
  transactionId: string;
  type: 'sale_payment' | 'platform_commission' | 'seller_payout' | 'subscription' | 'refund' | 'dispute';
  buyer?: (number | null) | User;
  seller?: (number | null) | User;
  user?: (number | null) | User;
  object?: (number | null) | Object;
  /**
   * Montant de la transaction en euros
   */
  amount: number;
  buyerCommission?: number | null;
  sellerCommission?: number | null;
  /**
   * Commission totale prélevée par la plateforme
   */
  platformRevenue?: number | null;
  status: 'pending' | 'processing' | 'completed' | 'failed' | 'refunded' | 'canceled';
  paymentMethod?: ('card' | 'bank_transfer' | 'paypal' | 'stripe') | null;
  /**
   * ID Stripe du paiement
   */
  stripePaymentIntentId?: string | null;
  /**
   * ID Stripe du versement au vendeur
   */
  stripeTransferId?: string | null;
  processedAt?: string | null;
  completedAt?: string | null;
  /**
   * Description détaillée de la transaction
   */
  description?: string | null;
  /**
   * Notes internes pour l'administration
   */
  internalNotes?: string | null;
  /**
   * Données techniques supplémentaires (JSON)
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Numéro de facture généré
   */
  invoiceNumber?: string | null;
  /**
   * Lien vers la facture PDF
   */
  invoiceUrl?: string | null;
  /**
   * Année fiscale de la transaction
   */
  fiscalYear?: number | null;
  /**
   * Transaction rapprochée avec le relevé bancaire
   */
  isReconciled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: number | Subscription;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'feedback';
        value: number | Feedback;
      } | null)
    | ({
        relationTo: 'objects';
        value: number | Object;
      } | null)
    | ({
        relationTo: 'bids';
        value: number | Bid;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'settings';
        value: number | Setting;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  firstName?: T;
  lastName?: T;
  profilePhoto?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        postalCode?: T;
        country?: T;
      };
  isOver18?: T;
  companyName?: T;
  siret?: T;
  officialDocument?: T;
  website?: T;
  socialMedia?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        twitter?: T;
      };
  bankDetails?:
    | T
    | {
        iban?: T;
        bic?: T;
        accountHolderName?: T;
        bankDetailsVerified?: T;
      };
  acceptedTerms?: T;
  acceptedMandate?: T;
  acceptedGDPR?: T;
  newsletterSubscription?: T;
  accountStatus?: T;
  isBlocked?: T;
  blockReason?: T;
  blockReasonDetails?: T;
  blockedAt?: T;
  blockedBy?: T;
  currentSubscription?: T;
  subscriptionStatus?: T;
  stripeCustomerId?: T;
  stripeSubscriptionId?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  userType?: T;
  price?: T;
  trialPeriodDays?: T;
  description?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  isActive?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  user?: T;
  plan?: T;
  status?: T;
  currentPeriodStart?: T;
  currentPeriodEnd?: T;
  trialEnd?: T;
  canceledAt?: T;
  autoRenew?: T;
  paymentMethod?: T;
  amount?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback_select".
 */
export interface FeedbackSelect<T extends boolean = true> {
  user?: T;
  stars?: T;
  npsScore?: T;
  comment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "objects_select".
 */
export interface ObjectsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  description?: T;
  dimensions?:
    | T
    | {
        length?: T;
        width?: T;
        height?: T;
        weight?: T;
      };
  documents?:
    | T
    | {
        document?: T;
        description?: T;
        id?: T;
      };
  photos?:
    | T
    | {
        photo?: T;
        id?: T;
      };
  price?: T;
  saleMode?: T;
  auctionConfig?:
    | T
    | {
        startingPrice?: T;
        reservePrice?: T;
        duration?: T;
        startDate?: T;
        endDate?: T;
        currentBid?: T;
        bidCount?: T;
      };
  seller?: T;
  status?: T;
  buyer?: T;
  soldPrice?: T;
  soldDate?: T;
  views?: T;
  favorites?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bids_select".
 */
export interface BidsSelect<T extends boolean = true> {
  object?: T;
  bidder?: T;
  amount?: T;
  bidType?: T;
  maxAutoBid?: T;
  status?: T;
  notified?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  image?: T;
  parentCategory?: T;
  order?: T;
  isActive?: T;
  featuredOnHome?: T;
  customCommissions?:
    | T
    | {
        useCustomCommissions?: T;
        buyerCommission?: T;
        sellerCommission?: T;
      };
  formCustomization?:
    | T
    | {
        additionalFields?:
          | T
          | {
              fieldName?: T;
              fieldLabel?: T;
              fieldType?: T;
              isRequired?: T;
              id?: T;
            };
        requireCertificate?: T;
        requireExpertise?: T;
      };
  objectCount?: T;
  activeAuctionsCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  label?: T;
  key?: T;
  globalCommissions?:
    | T
    | {
        buyerCommission?: T;
        sellerCommission?: T;
      };
  categoryCommissions?:
    | T
    | {
        category?: T;
        buyerCommission?: T;
        sellerCommission?: T;
        id?: T;
      };
  formConfig?:
    | T
    | {
        requiredFields?:
          | T
          | {
              fieldName?: T;
              id?: T;
            };
        minPhotos?: T;
        maxPhotos?: T;
        enableCertificates?: T;
        enableExpertise?: T;
      };
  generalSettings?:
    | T
    | {
        maintenanceMode?: T;
        registrationEnabled?: T;
        auctionEnabled?: T;
        quickSaleEnabled?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  transactionId?: T;
  type?: T;
  buyer?: T;
  seller?: T;
  user?: T;
  object?: T;
  amount?: T;
  buyerCommission?: T;
  sellerCommission?: T;
  platformRevenue?: T;
  status?: T;
  paymentMethod?: T;
  stripePaymentIntentId?: T;
  stripeTransferId?: T;
  processedAt?: T;
  completedAt?: T;
  description?: T;
  internalNotes?: T;
  metadata?: T;
  invoiceNumber?: T;
  invoiceUrl?: T;
  fiscalYear?: T;
  isReconciled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}